Hw3 task2 new
Furetur/CProgramming pull request #16
Opened 2020-03-25 09:13 UTC by Furetur

2020-05-07 17:25 UTC, SpirinEgor requested changes

2020-05-07 17:25 UTC, SpirinEgor commented on hw3/3.2.c
> +    FILE *file = fopen("file.txt", "r");
А файла нет в pr

2020-05-07 17:25 UTC, SpirinEgor commented on hw3/3.2.c
> +        }
`curLineEmpty &= <...>`

2020-05-12 15:01 UTC, Furetur commented on hw3/3.2.c
> +        }
Я заменил if на такую конструкцию, но она мне кажется менее читабельной

2020-05-20 11:02 UTC, SpirinEgor reviewed
конфликт при мердже

2020-05-20 11:02 UTC, SpirinEgor commented on hw3/3.2.c
> +    while(!endOfFile)
Пробела не хватает :)

2020-05-26 19:32 UTC, SpirinEgor approved these changes

2020-05-26 19:34 UTC, merged