Hw5 task3 new
Furetur/CProgramming pull request #20
Opened 2020-03-25 09:15 UTC by Furetur

2020-05-20 11:28 UTC, SpirinEgor requested changes
Тут все замечание такие же, как и в 5.1 и 5.2

2020-05-26 16:02 UTC, Furetur commented
Сдам после 5.1 и 5.2, так как является просто их объединением.
Потом просто подтяну из них изменения.

2020-06-01 12:24 UTC, SpirinEgor requested changes

2020-06-01 12:24 UTC, SpirinEgor commented on hw5/5.3.c
> +    else
Лучше в `if` сделать `return 0;`, а тут обойтись без `else`. Позволить избежать лишний уровень вложенности

2020-06-01 12:24 UTC, SpirinEgor commented on hw5/5.3.c
> +        else
И тут аналогично, лучше проверить это и сделать `return`

2020-06-01 13:37 UTC, SpirinEgor requested changes

2020-06-01 13:37 UTC, SpirinEgor commented on hw5/5.3.c
> +    if(!isPostfixExpressionValid(postfixExpression))
Тут пробел

2020-06-01 13:37 UTC, SpirinEgor commented on hw5/5.3.c
> +    }
Это можно без `else` опять же, если сделать `return 0;` выше

2020-06-01 14:17 UTC, SpirinEgor approved these changes

2020-06-01 14:17 UTC, merged