Hw9 task1 new
Furetur/CProgramming pull request #24
Opened 2020-03-25 09:16 UTC by Furetur

2020-05-20 12:27 UTC, SpirinEgor requested changes
Поправить согласно прошлым пр

2020-05-20 12:27 UTC, SpirinEgor commented on hw9/machine/machine.c
> +    return false;
.

2020-05-26 16:46 UTC, Furetur commented on hw9/machine/machine.c
> +    return false;
(༎ຶ⌑༎ຶ)

2020-06-03 16:10 UTC, SpirinEgor approved these changes

2020-06-03 16:10 UTC, merged